on:
  push:
    branches: 
      - main
      - zl-dev-1
  workflow_dispatch:

jobs:
  
  Pipeline-Scan:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.3

      - name: Setup Veracode
        run: |
         curl -fsS https://tools.veracode.com/veracode-cli/install | sh

      - name: Package App
        run: |
         pwd;
         ./veracode package -s . --output verascan -a

      - name: SAST Scan
        continue-on-error: true
        env:
         VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
         VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
        run: |
         ./veracode static scan /home/runner/work/verademo-js/verademo-js/verascan/veracode-auto-pack-verademo-js-js.zip
      
      - name: Upload SAST issues artifact
        uses: actions/upload-artifact@v4.3.3
        with:
           name: results.json
           path: "./results.json"

  Fix-Flaws:
    needs: Pipeline-Scan
    runs-on: [ubuntu-latest]
    permissions: write-all
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.3


      - name: Download flaws artifact
        uses: actions/download-artifact@v4
        with:
          name: results.json

      - name: Fix Findings
        uses: veracode/veracode-fix@v1.0.4
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          inputFile: results.json
          language: javascript
          cwe: 78,89,117,601,614 # SQL Injection and OS Command Injection
          fixType: 'batch'
          debug: false
          prComment: true
          files: 'all'
          codeSuggestion: false
          createPR: true
